version: "3"

services:
    influxdb:
        image: influxdb
        container_name: influxdb
        env_file: certbot.env
        ports: 
            - "8086:8086"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - ./influxdb:/var/lib/influxdb
        networks: 
            - "iotstack"

    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/log:/mosquitto/log
            - ./mosquitto/data:/mosquitto/data
        user: "1883"
        ports:
            - "8083:8083"
        links: 
            - telegraf
        restart: always
        networks: 
            - "iotstack"
    
    telegraf:
        image: telegraf
        container_name: telegraf
        links: 
            - influxdb
        env_file: certbot.env
        volumes: 
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        networks: 
            - "iotstack"
    
    grafana:
        image: grafana/grafana
        container_name: grafana
        ports: 
            - "3000:3000"
        env_file: certbot.env
        user: "0"
        links: 
            - influxdb
        volumes: 
            - ./grafana/data:/var/lib/grafana
            - /etc/letsencrypt:/etc/letsencrypt
        networks: 
            - "iotstack"

volumes: 
    influxdb:
    grafana:

networks: 
    iotstack:
